# Optical Bloch equations

$H_{int}^I=\frac{\hbar \Omega}{2} \sigma_{+} e^{i \eta (a e^{-i\omega_zt}+a^+ e^{i\omega_zt})}e^{i(-\delta t+\phi)}+h.c.$

Back to the Schrodinger picture

$H_{int}=\frac{\hbar \Omega}{2} (\sigma_{+} e^{i(\eta (a+a^+)-\omega_C t+\phi)}+\sigma_{-}e^{-i(\eta (a+a^+)-\omega_C t+\phi)})$


The total hamiltonian is 

$H=H^{(m)}+H^{(e)}+H^{(i)}= \hbar \omega_z (a^{+}a+\frac{1}{2})+\hbar \frac{\omega}{2} \sigma_z+ \frac{\hbar \Omega}{2} (\sigma_{+} e^{i(\eta (a+a^+)-\omega_C t+\phi)}+\sigma_{-}e^{-i(\eta (a+a^+)-\omega_C t+\phi)})$

To a frame rotating with the laser frequency $\omega_C$, defined by $U_C=e^{-i\frac{\omega_C}{2} \sigma_z t}$. The transformed hamiltonian is 

$\tilde{H}=U_C^+HU_C-\hbar \frac{\omega_C}{2} \sigma_z = \hbar \omega_z (a^{+}a+\frac{1}{2})-\hbar \frac{\delta}{2} \sigma_z+ \frac{\hbar \Omega}{2} (\sigma_{+} e^{i(\eta (a+a^+)+\phi)}+\sigma_{-}e^{-i(\eta (a+a^+)+\phi)})$

where $\delta=\omega_C-\omega$ is the detuning.

Effective Rabi frequency

$\Omega_{n, m}=\Omega_{m, n}=\Omega \mid \langle m \mid e^{i\eta (a+a^+)}\mid n \rangle \mid$


The transformed density matrix $\tilde{\rho}=U_C^+\rho U_C$ satisfies the same master equation (Denote $\tilde{\rho}=\rho$ in the following)

$\frac{d \rho}{dt}=-\frac{i}{\hbar}[\tilde{H}, \rho]+L^d \rho$

where $L^d \rho=\frac{\Gamma}{2}\{ 2\sigma^-  \tilde{\rho} \sigma^+ -\sigma^+ \sigma^-  \rho - \rho \sigma^+ \sigma^- \}$

$\tilde{\rho} = \frac{1}{2} \int_{-1}^1 du Y(u) e^{i \eta (a+a^+) u} \rho e^{-i \eta (a+a^+) u}$

$Y(u)=\frac{3}{4}(1+u)^2$ accounts for the angular distribution pattern of spontaneous emission for a dipole transition 

Then ($i, j, k,\in \{ e, g\}, \ n, m, l, f \in \{ 0,1,2,...\}$)

$\langle i,n \mid[\tilde{H}, \rho] \mid j, m \rangle = \hbar \omega_z (n-m) \{ \langle i,n \mid \rho \mid j, m \rangle -\hbar \frac{\delta}{2} \{ \langle e,n \mid \rho \mid j, m \rangle \delta_{ie}- \langle g,n \mid \rho \mid j, m \rangle \delta_{ig}  -\langle i,n \mid \rho \mid e, m \rangle  \delta_{je} +\langle i,n \mid \rho \mid g, m \rangle \delta_{jg} \}+\\
\frac{\hbar}{2} \sum_l \{  \Omega_{nl} \langle g,l \mid \rho \mid j, m \rangle \delta_{ie}+\Omega_{l n} \langle e,l \mid \rho \mid j, m \rangle \delta_{ig}-\Omega_{l m} \langle i,n \mid \rho \mid e, l \rangle \delta_{jg}-\Omega_{m l} \langle i,n \mid \rho \mid g, l \rangle \delta_{je}\} $

$\langle i,n \mid L^d \rho \mid j, m \rangle = \frac{\Gamma}{2}\sum_{l,f}\frac{1}{2}\int_{-1}^1Y(u)du A_{nl}(u)A_{mf}(u)\langle e,l \mid \rho \mid e, f \rangle \delta_{ig}\delta_{jg} -\frac{\Gamma}{2} \sum_l \{  \langle e,l \mid \rho \mid j, m \rangle \delta_{ie}+ \langle i,n \mid \rho \mid e, l \rangle \delta_{je} \}$

where $A_{mn}(u)= \langle m \mid e^{i\eta (a+a^+)u}\mid n \rangle$

$\langle i,n \mid L^d \rho \mid j, m \rangle = \frac{\Gamma}{2}\sum_{l,f}\int_{-1}^1Y(u)du A_{nl}(u)A_{mf}(u)\langle e,l \mid \rho \mid e, f \rangle \delta_{ig}\delta_{jg} -\frac{\Gamma}{2}  \{  \langle e,n \mid \rho \mid j, m \rangle \delta_{ie}+ \langle i,n \mid \rho \mid e, m \rangle \delta_{je} \} $ 

(1-16-17)

Or written explicitly, the optical Bloch equations are

$\frac{d \langle e,n \mid \rho \mid e, m \rangle}{dt}= -i\omega_z (n-m) \{ \langle e,n \mid \rho \mid e, m \rangle -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle e,n \mid \rho \mid g, l \rangle \} -\frac{\Gamma}{2} \sum_l \{  \langle e,l \mid \rho \mid e, m \rangle + \langle e,n \mid \rho \mid e, l \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid g, m \rangle}{dt} = -i\omega_z (n-m) \{ \langle g,n \mid \rho \mid g, m \rangle-\frac{i}{2} \sum_l \{  \Omega_{ln} \langle e,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle g,n \mid \rho \mid e, l \rangle \} +\frac{\Gamma}{2}\sum_{l,f}\frac{1}{2}\int_{-1}^1 du Y(u) A_{nl}(u)A_{mf}(u)\langle e,l \mid \rho \mid e, f \rangle$

$\frac{d \langle e,n \mid \rho \mid g, m \rangle}{dt} = -i\{\omega_z (n-m)- \delta  \}\langle e,n \mid \rho \mid g, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle e,n \mid \rho \mid e, l \rangle \}-\frac{\Gamma}{2} \sum_l \{  \langle e,l \mid \rho \mid g, m \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid e, m \rangle}{dt} = i\{-\omega_z (n-m) - \delta\}  \langle g,n \mid \rho \mid e, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{l n} \langle e,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle g,n \mid \rho \mid g, l \rangle \}-\frac{\Gamma}{2} \sum_l \{  \langle g,n \mid \rho \mid e,l \rangle  \}$

Or written explicitly, the optical Bloch equations are

$\frac{d \langle e,n \mid \rho \mid e, m \rangle}{dt}= -i\omega_z (n-m) \{ \langle e,n \mid \rho \mid e, m \rangle -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle e,n \mid \rho \mid g, l \rangle \} -\Gamma  \{  \langle e,n \mid \rho \mid e, m \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid g, m \rangle}{dt} = -i\omega_z (n-m) \{ \langle g,n \mid \rho \mid g, m \rangle-\frac{i}{2} \sum_l \{  \Omega_{ln} \langle e,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle g,n \mid \rho \mid e, l \rangle \} +\frac{\Gamma}{2}\sum_{l,f}\int_{-1}^1 du Y(u) A_{nl}(u)A_{mf}(u)\langle e,l \mid \rho \mid e, f \rangle$

$\frac{d \langle e,n \mid \rho \mid g, m \rangle}{dt} = -i\{\omega_z (n-m)- \delta  \}\langle e,n \mid \rho \mid g, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle e,n \mid \rho \mid e, l \rangle \}-\frac{\Gamma}{2} \{  \langle e,n \mid \rho \mid g, m \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid e, m \rangle}{dt} = i\{-\omega_z (n-m) - \delta\}  \langle g,n \mid \rho \mid e, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{l n} \langle e,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle g,n \mid \rho \mid g, l \rangle \}-\frac{\Gamma}{2}  \{  \langle g,n \mid \rho \mid e,m \rangle  \}$ 

(1-16-17)

If define an effective spontaneous decay

$\Gamma_{nl,mf}=\Gamma \frac{1}{2}\int_{-1}^1 du Y(u) A_{nl}(u)A_{mf}(u)$

The optical Bloch equations are

$\frac{d \langle e,n \mid \rho \mid e, m \rangle}{dt}= -i\omega_z (n-m) \{ \langle e,n \mid \rho \mid e, m \rangle -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle e,n \mid \rho \mid g, l \rangle \} -\frac{\Gamma}{2} \sum_l \{  \langle e,l \mid \rho \mid e, m \rangle + \langle e,n \mid \rho \mid e, l \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid g, m \rangle}{dt} = -i\omega_z (n-m) \{ \langle g,n \mid \rho \mid g, m \rangle-\frac{i}{2} \sum_l \{  \Omega_{ln} \langle e,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle g,n \mid \rho \mid e, l \rangle \} +\frac{1}{2}\sum_{l,f}\Gamma_{nl,mf}\langle e,l \mid \rho \mid e, f \rangle$


$\frac{d \langle e,n \mid \rho \mid g, m \rangle}{dt} = -i\{\omega_z (n-m)- \delta  \}\langle e,n \mid \rho \mid g, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{n l} \langle g,l \mid \rho \mid g, m \rangle -\Omega_{l m} \langle e,n \mid \rho \mid e, l \rangle \}-\frac{\Gamma}{2} \sum_l \{  \langle e,l \mid \rho \mid g, m \rangle  \}$

$\frac{d \langle g,n \mid \rho \mid e, m \rangle}{dt} = i\{-\omega_z (n-m) - \delta\}  \langle g,n \mid \rho \mid e, m \rangle  -\frac{i}{2} \sum_l \{  \Omega_{l n} \langle e,l \mid \rho \mid e, m \rangle -\Omega_{m l} \langle g,n \mid \rho \mid g, l \rangle \}-\frac{\Gamma}{2} \sum_l \{  \langle g,n \mid \rho \mid e,l \rangle  \}$


## Previously wrong versions

Optical Bloch equations

$\frac{d \rho_{ij}}{dt}=-\frac{\Gamma}{2}\rho_{ij} + i \sum_k (\rho_{ik} \Omega_{kj}-\rho_{kj}\Omega_{ik})$

$\frac{d \rho_{ii}}{dt} = -\Gamma \rho_{ii}+ i \sum_k (\rho_{ik} \Omega_{ki}-\rho_{ki}\Omega_{ik})$

Can be solved by simulation

Or should I write the spontaneous emission as

$\Gamma_{n,m}=\Gamma \mid \langle n \mid e^{i\eta (a+a^+)}\mid m \rangle \mid$

Optical Bloch equations

$\frac{d \rho_{ij}}{dt}=-\frac{1}{2} \sum_k (\Gamma_{ki} +\Gamma_{kj})\rho_{ij} + i \sum_k (\rho_{ik} \Omega_{kj}-\rho_{kj}\Omega_{ik})$

$\frac{d \rho_{ii}}{dt} = \sum_k \Gamma_{ik} \rho_{kk}-\sum_k\Gamma_{ki} \rho_{ii}+ i \sum_k (\rho_{ik} \Omega_{ki}-\rho_{ki}\Omega_{ik})$

# Rate equations

## Near saturation case

The rate of absorption-emission cycles is given by the scattering rate

$R_{scatt}(\delta)=\Gamma \rho_{22}= \Gamma \frac{\Omega^2/4}{\delta^2+\Omega^2/2+\Gamma^2/4}$

$\delta=-\omega_z$ red sideband on resonance, carrier detuning $\omega_z$, blue sideband detuning $2\omega_z$

$R_{rsb}= \Gamma \frac{(n) \eta^2 \Omega^2/4}{(n) \eta^2 \Omega^2/2+\Gamma^2/4} \simeq \Gamma$

$R_{bsb}= \Gamma \frac{(n+1) \eta^2 \Omega^2/4}{\omega_z^2+(n+1) \eta^2 \Omega^2/2+\Gamma^2/4} \simeq \Gamma \frac{(n+1) \eta^2 \Omega^2/4}{\omega_z^2+(n+1) \eta^2 \Omega^2/2}$

$R_{carrier}= \Gamma \frac{ \Omega^2/4}{4 \omega_z^2+ \Omega^2/2+\Gamma^2/4} \simeq \Gamma \frac{ \Omega^2/4}{4 \omega_z^2+\eta^2 \Omega^2/2}$

Denote $P_n$ the population of $\mid g,n \rangle $. In the Lamb-Dicke limit 

$\frac{d P_n}{dt}=A_{1}P_{n-1}+A_{2}P_{n+1}-A_{3} P_n-A_{4}Pn$

where $ A_{1} = R_{bsb}+R_{carrier}\eta'^2= \Gamma \frac{ n\eta^2 \Omega^2/4}{\omega_z^2+n \eta^2 \Omega^2/2}+\Gamma \eta'^2\frac{ \Omega^2/4}{4 \omega_z^2+\eta^2 \Omega^2/2}$

$ A_{2}=R_{rsb}+R_{carrier}\eta'^2=\Gamma +\Gamma \eta'^2\frac{ \Omega^2/4}{4 \omega_z^2+\eta^2 \Omega^2/2}$

$ A_{3} = R_{bsb}+R_{carrier}\eta'^2= \Gamma \frac{ (n+1)\eta^2 \Omega^2/4}{\omega_z^2+(n+1) \eta^2 \Omega^2/2}+\Gamma \eta'^2\frac{ \Omega^2/4}{4 \omega_z^2+\eta^2 \Omega^2/2}$

$ A_{4}=R_{rsb}+R_{carrier}\eta'^2=\Gamma +\Gamma \eta'^2\frac{ \Omega^2/4}{4 \omega_z^2+\eta^2 \Omega^2/2}$



Define the average excitation number $\langle n \rangle =\sum_{n=0}^{\infty} n P_n$

$\frac{d\langle n\rangle}{dt}=...=(A_1-A_3)\langle n\rangle +\sum_n(A_1-A_2)P_n=-B_1\langle n\rangle +B_2$



where $B_1=\Gamma \frac{ (n+1)\eta^2 \Omega^2/4}{\omega_z^2+(n+1) \eta^2 \Omega^2/2}-\Gamma \frac{ n\eta^2 \Omega^2/4}{\omega_z^2+n \eta^2 \Omega^2/2} >0$

$B_2=\Gamma \frac{ n\eta^2 \Omega^2/4}{\omega_z^2+n \eta^2 \Omega^2/2}-\Gamma$

Cooling rate given by $B_1>0$, but very small when $n$ is large.

$B_{1,max}=\Gamma \frac{ \eta^2 \Omega^2/4}{\omega_z^2+\eta^2 \Omega^2/2}$

Steady state $\langle n\rangle =\frac{B_2}{B_1}<0$

$\eta =0.2, \omega_z =2\pi \times 500 Hz, \Omega = 100 \ rad/s, \Gamma_e = 2\pi \times1 mHz$ (Nicholson, pp44)

In [30]:
pi = 3.14
eta = 0.2
Omega = 100
Gamma = 2*pi*0.001
omega_z = 2*pi*500
B=Gamma*(eta*Omega/2)**2/(omega_z**2+(eta*Omega)**2/2)
print B

6.36929755167e-08


Still very slow

## Far below saturation case

Lamb-Dicke limit & laser power below saturation, $\eta \sqrt{n} \Omega \ll \delta$  

(Or assume precooling has lead to a good state, see below)

$\frac{d P_n}{dt}=nA_{+}P_{n-1}+(n+1)A_{-}P_{n+1}-(n+1)A_{+} P_n-nA_{-}Pn$

where $A_{+} =\eta^2 \Gamma \frac{\Omega^2/4}{\delta_{bsb}^2+\Gamma^2/4}+\eta'^2 \Gamma\frac{\Omega^2/4}{\delta_{carrier}^2+\Gamma^2/4}$

$A_{-}=\eta^2 \Gamma \frac{\Omega^2/4}{\delta_{rsb}^2+\Gamma^2/4}+\eta'^2 \Gamma\frac{\Omega^2/4}{\delta_{carrier}^2+\Gamma^2/4}$

$\frac{d\langle n\rangle}{dt}=...=-(A_{-}-A_{+})\langle n\rangle+A_{+} $

Cooling: $\delta=-\omega_z$ red sideband on resonance, carrier detuning $\omega_z$, blue sideband detuning $2\omega_z$

$A_{+} =\eta^2 \Gamma \frac{\Omega^2/4}{\omega_z^2+\Gamma^2/4}+\eta'^2 \Gamma\frac{\Omega^2/4}{4\omega_z^2+\Gamma^2/4}$

$ A_{-}=\eta^2 \Gamma \frac{\Omega^2/4}{\Gamma^2/4}+\eta'^2 \Gamma\frac{\Omega^2/4}{4\omega_z^2+\Gamma^2/4}$


Cooling rate

$A_{-}-A_{+}=\eta^2 \Gamma (\frac{\Omega^2}{\Gamma^2}-\frac{\Omega^2/4}{\omega_z^2+\Gamma^2/4})=\eta^2 \Gamma (\frac{\Omega^2}{\Gamma^2}-\frac{s}{2})$

where $s=\frac{I}{I_{sat}}=2\frac{\Omega^2}{\Gamma^2}\frac{\Gamma^2/4}{\delta^2+\Gamma^2/4}$ is the saturation parameter of $\delta = \omega_z$

$\eta =0.2, \omega_z =2\pi \times 500 Hz, \Omega = 100 \ rad/s, \Gamma_e = 2\pi \times1 mHz$ (Nicholson, pp44)

In [26]:
pi = 3.14
eta = 0.2
Omega = 100
Gamma = 2*pi*0.001
omega_z = 2*pi*500
s = 2*(Omega/Gamma)**2*(Gamma**2/4)/(omega_z**2+Gamma**2/4)
A = eta**2*Gamma*((Omega/Gamma)**2-s/2)
print 's=',s, 'A=',A, '(Omega/Gamma)^2=', (Omega/Gamma)**2

s= 0.000507119964298 A= 63694.2675159 (Omega/Gamma)^2= 253559982.149


Obviously, the red sideband scattering rate is overestimated in this easy case.

Otherwise can we broaden the excited state to make $Gamma$ larger?

Moreover, the condition for the good state is

$\eta \sqrt{n} \Omega \ll \omega_z, \Gamma$

$n  \ll (\frac{\Gamma}{\Omega \eta})^2$

In [20]:
(Gamma/Omega*eta)**2

1.577536e-10

Ridiculous!

Steady state 

$\langle n\rangle=\frac{A_{+}}{A_{-}-A_{+}}\simeq \frac{\frac{5}{4}\frac{\Omega^2/4}{\omega_z^2}}{ \frac{\Omega^2}{\Gamma^2}-\frac{\Omega^2/4}{\omega_z^2}}=\frac{5/4}{4\frac{\omega_z^2}{\Gamma^2}-1}$

In [31]:
5/4/((2*omega_z/Gamma)**2-1)

1.000000000001e-12

Very good

# Spectroscopy to estimate the final average excitation

Thermal distribution of harmonic oscillator:

$T=\frac{\hbar \omega_z}{k_B ln(\frac{\bar{n}+1}{\bar{n}})}$

Density matrix

$\rho=\frac{1}{\bar{n}+1} \sum_{n=0}^{\infty} (\frac{\bar{n}}{\bar{n}+1})^n \mid n\rangle \langle n \mid$

In [46]:
###################
# Test for the code
###################

In [1]:
from numpy import *
_thetas = r_[-1: 1: 91j]
print _thetas

[-1.         -0.97777778 -0.95555556 -0.93333333 -0.91111111 -0.88888889
 -0.86666667 -0.84444444 -0.82222222 -0.8        -0.77777778 -0.75555556
 -0.73333333 -0.71111111 -0.68888889 -0.66666667 -0.64444444 -0.62222222
 -0.6        -0.57777778 -0.55555556 -0.53333333 -0.51111111 -0.48888889
 -0.46666667 -0.44444444 -0.42222222 -0.4        -0.37777778 -0.35555556
 -0.33333333 -0.31111111 -0.28888889 -0.26666667 -0.24444444 -0.22222222
 -0.2        -0.17777778 -0.15555556 -0.13333333 -0.11111111 -0.08888889
 -0.06666667 -0.04444444 -0.02222222  0.          0.02222222  0.04444444
  0.06666667  0.08888889  0.11111111  0.13333333  0.15555556  0.17777778
  0.2         0.22222222  0.24444444  0.26666667  0.28888889  0.31111111
  0.33333333  0.35555556  0.37777778  0.4         0.42222222  0.44444444
  0.46666667  0.48888889  0.51111111  0.53333333  0.55555556  0.57777778
  0.6         0.62222222  0.64444444  0.66666667  0.68888889  0.71111111
  0.73333333  0.75555556  0.77777778  0.8         0

In [3]:
a=array([0,1])
print a

[0 1]


In [2]:
from numpy import *
n=5
ps0 = exp(-arange(n + 1, dtype=complex128) / 10) * (1 - exp(1 / 10))
rho0 = diag(r_[ps0, zeros(n + 1, dtype=complex128)])
print(ps0)
print(sum(rho0))
#print rho0

[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
0j


In [22]:
def f(t,y):
    return  array([y[1], -y[0]])

In [15]:
arange(4)

array([0, 1, 2, 3])

In [25]:
print b.T[0]

[140564281042968         9545840               0               0
        18567408]


In [11]:
a11 = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
a22 = np.array([[1, 2, 3], [4, 5, 10]], np.int32)
a12 = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
a21 = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
rho=array([a11, a22, a12])
print rho
print rho[1][1,2]
print 3*rho[1]
print rho[1][1,:].sum()

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5 10]]

 [[ 1  2  3]
  [ 4  5  6]]]
10
[[ 3  6  9]
 [12 15 30]]
19


In [12]:
# m, n, s = rho.shape
res = zeros(3+1, dtype=complex128)
#print rho.shape
print res
res[:4]

[ 0.+0.j  0.+0.j  0.+0.j  0.+0.j]


array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j])

In [8]:
range(3)

[0, 1, 2]

In [54]:
2>=3

False

In [3]:
import numpy as np
a11 = np.array([[1+1j, 2+ 2j, 3+3j], [4+4j, 5+5j, 6+6j]], dtype=complex)
a22 = np.array([[1, 2, 3], [4, 5, 10]], dtype=complex)
print a11
print a11.transpose().conjugate()
print (a11*a22)
print (a11*a22).sum()

c = np.array([1+1j], dtype=complex)
d = np.array([1+2j], dtype=complex)
print c.dot(d)

[[ 1.+1.j  2.+2.j  3.+3.j]
 [ 4.+4.j  5.+5.j  6.+6.j]]
[[ 1.-1.j  4.-4.j]
 [ 2.-2.j  5.-5.j]
 [ 3.-3.j  6.-6.j]]
[[  1. +1.j   4. +4.j   9. +9.j]
 [ 16.+16.j  25.+25.j  60.+60.j]]
(115+115j)
(-1+3j)


In [2]:

from numpy import *
a=zeros([2,3])
a[1,1]=1
empty((1,2), complex128)
print a

[[ 0.  0.  0.]
 [ 0.  1.  0.]]


In [15]:
range(-3,3)
2 in range(-3,3)
for i in range(max(-3, 0), 3):
  print (i**3)
range(3)

0
1
8


[0, 1, 2]

In [69]:
zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [71]:
zeros((9,9))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [86]:
b = np.array([[1, 2], [4, 5]], np.int32)
zeros_like(b).shape

(2, 2)

In [9]:
arange(1, 20)
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a11 = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], int32)
print (a11)
m,n = a11.shape
trap = zeros_like(a11)
for i in range(m):
    for j in range(n):
        trap[i, j] = i-j
        
print trap
print trap * a11
print abs(diag(a11))
print a11[1, :]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
[[ 0 -2 -6]
 [ 4  0 -6]
 [14  8  0]]
[1 5 9]
[4 5 6]


In [28]:
a = 1+ 2j
real(a)

array(1.0)

In [43]:
    import numpy.random as random
    rho = random.rand(5,5)
    print rho
    index = zeros([5,5])
    for i in range(5):
        for j in range(5):
            index[i, j] = i - j
    print index
    print index*rho
    print (index*rho).sum()
    

[[ 0.16389904  0.37777357  0.05304501  0.70674642  0.80592367]
 [ 0.42373906  0.59756359  0.074729    0.69061415  0.99709579]
 [ 0.71105384  0.7362923   0.09131923  0.04651974  0.7023137 ]
 [ 0.12211219  0.70651312  0.87636112  0.52024919  0.45886841]
 [ 0.78189827  0.98756403  0.8721147   0.76856627  0.32832113]]
[[ 0. -1. -2. -3. -4.]
 [ 1.  0. -1. -2. -3.]
 [ 2.  1.  0. -1. -2.]
 [ 3.  2.  1.  0. -1.]
 [ 4.  3.  2.  1.  0.]]
[[ 0.         -0.37777357 -0.10609002 -2.12023927 -3.22369467]
 [ 0.42373906  0.         -0.074729   -1.3812283  -2.99128737]
 [ 1.42210767  0.7362923   0.         -0.04651974 -1.40462741]
 [ 0.36633658  1.41302624  0.87636112  0.         -0.45886841]
 [ 3.1275931   2.9626921   1.7442294   0.76856627  0.        ]]
1.65588611367
